---
language: python
python:
  - "2.7"
services:
  - docker
install:
  - pip install -r pip-requirements.txt
script:
  - molecule --version
  - ansible --version
  - ansible-lint playbooks/*.yml
  - cd roles/docker-remote-api && molecule test
