- hosts: all

  vars:
    docker_install_compose: false
    docker_package_version: "19.03.5"
    docker_service_enabled: "yes"
    docker_service_state: "started"
    docker_swarm_interface: "eth1"
    skip_docker_py: true

  roles:
    - atosatto.docker-swarm
