- hosts: all

  vars:
    docker_install_compose: false
    docker_package_version: "19.03.5"
    docker_service_enabled: "yes"
    docker_service_state: "started"
    docker_swarm_interface: "eth1"

    sysctl_overwrite:
      net.ipv4.ip_forward: 1

  roles:
    - dev-sec.os-hardening
    - atosatto.docker-swarm
    - docker-remote-api
